### ISSUE TITLE
Provide archive.org-mirror to work around data quota

### ISSUE THREAD

**Issue by Kristine1975** [LemonHaze420/SOS2002#1]
Currently, doing a `git clone --depth 1 https://github.com/LemonHaze420/SOS2002` fails when git tries to download the LFS data: 

> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

(see https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage)

Please upload this repository's data (or maybe even the original 3GB archive) to archive.org, so it can be downloaded without problems.

**Comment by LemonHaze420** [comment]
This should be resolved now, let me know if it works for you.

**Comment by Kristine1975** [comment]
Can confirm that it works. Thank you for fixing this!
